* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
FREQUENCIES VARIABLES=Favorite FavoriteToy
  /BARCHART PERCENT
  /ORDER=ANALYSIS.

EXAMINE VARIABLES=DaysToFail BY Breed
  /PLOT BOXPLOT HISTOGRAM
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.
